# Generated by Django 5.0.4 on 2024-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovion_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='average_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
